Repository mundipagg/magento, pull requests merged in 2018-04, with the labels that each got.

#58 Module i18n
  app/code/community/Mundipagg/Paymentmodule/Block/Base.php
  app/code/community/Mundipagg/Paymentmodule/Block/Checkout/Information.php
  app/code/community/Mundipagg/Paymentmodule/Block/Customer/Account/Wallet.php
  app/code/community/Mundipagg/Paymentmodule/Block/Form/Builder.php
  app/code/community/Mundipagg/Paymentmodule/Block/Form/Partial/Boleto.php
  app/code/community/Mundipagg/Paymentmodule/Block/Form/Partial/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Block/Form/Partial/Grandtotal.php
  app/code/community/Mundipagg/Paymentmodule/controllers/I18nController.php
  app/code/community/Mundipagg/Paymentmodule/etc/config.xml
  app/code/community/Mundipagg/Paymentmodule/etc/system.xml
  app/design/frontend/base/default/template/paymentmodule/checkout/information.phtml
  app/design/frontend/base/default/template/paymentmodule/form/partial/boleto.phtml
  app/design/frontend/base/default/template/paymentmodule/form/partial/creditcard.phtml
  app/locale/pt_BR/mundipagg_adminhtml_locale.csv
  app/locale/pt_BR/mundipagg_frontend_locale.csv
  js/mundipagg/paymentmodule.js
  modman
Labels: Feature, Ready

#59 Remove null coalesce operator
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Creditcard.php
Labels: Ready, enhancement

#60 Remove credit card data from backend
  app/design/frontend/base/default/template/paymentmodule/form/partial/creditcard.phtml
  composer.lock
  js/mundipagg/paymentmodule.js
Labels: Ready, bug

#61 Choose enabled brands when default installments option is enabled
  app/code/community/Mundipagg/Paymentmodule/Block/Form/Partial/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Installment.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Savedcreditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Config/Card.php
  app/code/community/Mundipagg/Paymentmodule/Model/Standard.php
  app/code/community/Mundipagg/Paymentmodule/etc/system.xml
  app/design/frontend/base/default/template/paymentmodule/form/partial/creditcard.phtml
  app/locale/pt_BR/mundipagg_frontend_locale.csv
  js/mundipagg/paymentmodule.js
Labels: Ready, bug

#62 Create multi buyer payment
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Boleto.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Boleto.php
  app/code/community/Mundipagg/Paymentmodule/Model/Config/Twocreditcards.php
  app/code/community/Mundipagg/Paymentmodule/Model/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Standard.php
  app/design/frontend/base/default/template/paymentmodule/form/partial/boleto.phtml
  app/design/frontend/base/default/template/paymentmodule/form/partial/creditcard.phtml
  app/locale/en_US/mundipagg_frontend_locale.csv
  app/locale/pt_BR/mundipagg_frontend_locale.csv
Labels: Feature, Ready

#63 Fix module break on saved card checkout
  app/design/frontend/base/default/template/paymentmodule/form/partial/creditcard.phtml
  js/mundipagg/paymentmodule.js
Labels: Ready, bug

#64 Mundipagg brand update
  app/code/community/Mundipagg/Paymentmodule/etc/system.xml
  app/locale/pt_BR/mundipagg_adminhtml_locale.csv
  skin/adminhtml/default/default/images/mundipagg/icons/logo-mundipagg-icon.png
  skin/adminhtml/default/default/images/mundipagg/mundipagg-colorida.svg
Labels: Ready, bug

#65 Fix amex doesn't transactioning
  js/mundipagg/paymentmodule.js
Labels: Ready, bug

#66 Fixed multipayment value input balance weird behavior
  app/design/frontend/base/default/template/paymentmodule/form/partial/creditcard.phtml
  js/mundipagg/paymentmodule.js
Labels: Ready, bug

#67 Improve module logging.
  app/code/community/Mundipagg/Paymentmodule/Helper/Exception.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Log.php
  app/code/community/Mundipagg/Paymentmodule/controllers/CreditcardController.php
  app/code/community/Mundipagg/Paymentmodule/controllers/I18nController.php
  app/code/community/Mundipagg/Paymentmodule/controllers/PaymentController.php
  app/code/community/Mundipagg/Paymentmodule/controllers/WalletController.php
  app/code/community/Mundipagg/Paymentmodule/controllers/WebhookController.php
Labels: Ready, enhancement

#68 Implement Multibuyer frontend
  app/code/community/Mundipagg/Paymentmodule/Block/Form/Builder.php
  app/code/community/Mundipagg/Paymentmodule/Block/Form/Partial/Multibuyer.php
  app/code/community/Mundipagg/Paymentmodule/Model/Config/Multibuyer.php
  app/code/community/Mundipagg/Paymentmodule/etc/system.xml
  app/design/frontend/base/default/template/paymentmodule/form/builder.phtml
  app/design/frontend/base/default/template/paymentmodule/form/partial/boleto.phtml
  app/design/frontend/base/default/template/paymentmodule/form/partial/creditcard.phtml
  app/design/frontend/base/default/template/paymentmodule/form/partial/multibuyer.phtml
  app/locale/pt_BR/mundipagg_adminhtml_locale.csv
  js/mundipagg/paymentmodule.js
Labels: Feature, Ready

#72 Add CI with CircleCI and Rancher
  .circleci/config.yml
  .circleci/data/Dockerfile
  .circleci/data/magento_module_install.sql
  .circleci/data/wait-for-mysql.sh
  README.md
  composer.lock
Labels: Feature, Ready, enhancement

#73 Added Multicurrency support.
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Boleto.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Standard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Boleto.php
  app/code/community/Mundipagg/Paymentmodule/Model/Boletocc.php
  app/code/community/Mundipagg/Paymentmodule/Model/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Standard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Twocreditcards.php
  composer.lock
  js/mundipagg/paymentmodule.js
Labels: Feature, Ready

#74 Fixes Multibuyer with boleto + credit cards
  app/code/community/Mundipagg/Paymentmodule/Block/Form/Builder.php
  app/design/frontend/base/default/template/paymentmodule/form/partial/multibuyer.phtml
  js/mundipagg/paymentmodule.js
Labels: Ready, bug
