Repository mundipagg/magento, pull requests merged in 2018-06, with the labels that each got.

#90 Guest Checkout Fixes
  app/code/community/Mundipagg/Paymentmodule/Helper/Address.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Boleto.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Standard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Observer.php
  app/code/community/Mundipagg/Paymentmodule/Model/Paymentmethods/Standard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Standard.php
  app/design/frontend/base/default/template/paymentmodule/checkout/information.phtml
Labels: Ready, bug

#91 Null address inputs handling
  app/code/community/Mundipagg/Paymentmodule/Helper/Address.php
  app/code/community/Mundipagg/Paymentmodule/Model/Paymentmethods/Standard.php
Labels: Ready, bug, enhancement

#93 Cancel and capture by module
  app/code/community/Mundipagg/Paymentmodule/Block/Adminhtml/Order/Charge/Grid.php
  app/code/community/Mundipagg/Paymentmodule/Block/Adminhtml/Order/Charge/Popup.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Chargeoperations.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Exception.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Order.php
  app/code/community/Mundipagg/Paymentmodule/Model/Paymentmethods/Standard.php
  app/code/community/Mundipagg/Paymentmodule/controllers/Adminhtml/ChargeController.php
  app/code/community/Mundipagg/Paymentmodule/controllers/ChargeController.php
  app/code/community/Mundipagg/Paymentmodule/controllers/WebhookController.php
  app/code/community/Mundipagg/Paymentmodule/etc/config.xml
  app/design/adminhtml/default/default/layout/paymentmodule.xml
  app/design/adminhtml/default/default/template/paymentmodule/chargePopup.phtml
  app/design/adminhtml/default/default/template/paymentmodule/extras.phtml
  app/locale/pt_BR/mundipagg_adminhtml_locale.csv
  js/mundipagg/ChargeController.js
  modman
Labels: Feature, Ready

#94 Fix cancel/capture failure handling
  app/code/community/Mundipagg/Paymentmodule/controllers/ChargeController.php
Labels: bug

#95 Show module version on config
  app/code/community/Mundipagg/Paymentmodule/Block/Adminhtml/Version.php
  app/code/community/Mundipagg/Paymentmodule/etc/system.xml
  app/locale/pt_BR/mundipagg_adminhtml_locale.csv
Labels: Feature, Ready

#97 Run modman in robofile and change configuration sort order
  RoboFile.php
  app/code/community/Mundipagg/Paymentmodule/etc/system.xml
Labels: Ready, enhancement

#98 Create from-to for address fields
  app/code/community/Mundipagg/Paymentmodule/Helper/Address.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Installment.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Interest.php
  app/code/community/Mundipagg/Paymentmodule/Model/Config/Address.php
  app/code/community/Mundipagg/Paymentmodule/Model/Config/Card.php
  app/code/community/Mundipagg/Paymentmodule/Model/Core/Order.php
  app/code/community/Mundipagg/Paymentmodule/Model/CreditCardOperationType.php
  app/code/community/Mundipagg/Paymentmodule/Model/StreetFields.php
  app/code/community/Mundipagg/Paymentmodule/controllers/WalletController.php
  app/code/community/Mundipagg/Paymentmodule/etc/config.xml
  app/code/community/Mundipagg/Paymentmodule/etc/system.xml
Labels: Feature, Ready

#99 Handle payment failed response
  app/code/community/Mundipagg/Paymentmodule/Helper/Chargeoperations.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Installment.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Interest.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Monetary.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Paymentformat.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Order.php
  app/code/community/Mundipagg/Paymentmodule/Model/Core/Charge.php
  app/code/community/Mundipagg/Paymentmodule/Model/Core/Order.php
  app/code/community/Mundipagg/Paymentmodule/Model/Paymentmethods/Standard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Standard.php
  app/code/community/Mundipagg/Paymentmodule/controllers/PaymentController.php
Labels: Ready, bug

#100 Get correct cpf field
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Standard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Boleto.php
  app/design/frontend/base/default/template/paymentmodule/checkout/information.phtml
  app/design/frontend/base/default/template/paymentmodule/form/partial/boleto.phtml
  app/design/frontend/base/default/template/paymentmodule/form/partial/multibuyer.phtml
  app/locale/pt_BR/mundipagg_frontend_locale.csv
Labels: Ready, bug
