Repository mundipagg/magento, pull requests merged in 2018-08, with the labels that each got.

#106 Implement functional tests
  .circleci/config.yml
  .circleci/data/magento_module_install.sql
  behat.yml
  composer.json
  composer.lock
  features/BuyWithCreditCard.feature
  features/bootstrap/FeatureContext.php
  modman
Labels: In development, enhancement

#110 Hide payment index when is single payment.
  app/code/community/Mundipagg/Paymentmodule/Block/Form/Builder.php
  app/design/frontend/base/default/template/paymentmodule/form/builder.phtml
  app/design/frontend/base/default/template/paymentmodule/form/partial/boleto.phtml
  app/design/frontend/base/default/template/paymentmodule/form/partial/creditcard.phtml
Labels: Ready, bug

#112 Fix credit card backend validation
  app/code/community/Mundipagg/Paymentmodule/Model/Creditcard.php
  composer.lock
Labels: Ready, bug

#114 Fixed charge screen broken
  app/code/community/Mundipagg/Paymentmodule/Block/Adminhtml/Order/Charge/Grid.php
  features/BuyWithTwoCreditCard.feature
Labels: Ready, bug

#115 Fix document filtering to accept only numbers send to api
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Standard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Standard.php
  app/design/frontend/base/default/template/paymentmodule/form/partial/multibuyer.phtml
  js/mundipagg/multibuyer.js
Labels: Ready, bug

#116 Create checksum validate
  .gitignore
  app/code/community/Mundipagg/Paymentmodule/Helper/MagentoSystemInfo.php
  app/code/community/Mundipagg/Paymentmodule/controllers/MaintenanceController.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/IntegrityController.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/IntegrityEngine.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/SystemInfoInterface.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/integrityCheck
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/modman
  composer.json
  composer.lock
  integrityDeploy.php
  modman
Labels: Feature, In development

#117 Create log maintenance
  app/code/community/Mundipagg/Paymentmodule/Helper/Log.php
  app/code/community/Mundipagg/Paymentmodule/Helper/MagentoSystemInfo.php
  app/code/community/Mundipagg/Paymentmodule/controllers/MaintenanceController.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/FileCompactor.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/IntegrityController.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/IntegrityEngine.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/README.md
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/SystemInfoInterface.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/integrityCheck
  integrityDeploy.php
Labels: Feature, In development

#119 Create order report
  app/code/community/Mundipagg/Paymentmodule/Helper/MagentoOrderInfo.php
  app/code/community/Mundipagg/Paymentmodule/Helper/MagentoSystemInfo.php
  app/code/community/Mundipagg/Paymentmodule/controllers/MaintenanceController.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/AbstractOrderInfo.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/FileCompactor.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/IntegrityController.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/IntegrityException.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/IntegrityViewer.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/OrderInfoInterface.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/SystemInfoInterface.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/integrityCheck
Labels: Feature, Ready

#120 create order report (FIX BUG)
  composer.json
Labels: Ready, bug

#122 Add pre-push hook
  .circleci/data/Dockerfile
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/integrityCheck
  behat.yml
  composer.json
  composer.lock
  crook.json
  integrityCheck.php
  integrityPrePushCheck.sh
  theHook
Labels: Feature, Ready, enhancement

#123 Added log configurations
  .circleci/data/magento_module_install.sql
  app/code/community/Mundipagg/Paymentmodule/Helper/Log.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Logger.php
  app/code/community/Mundipagg/Paymentmodule/Model/Config/Form/Log/Enabled.php
  app/code/community/Mundipagg/Paymentmodule/Model/Config/Form/Log/Hostname.php
  app/code/community/Mundipagg/Paymentmodule/Model/Config/Form/Log/Path.php
  app/code/community/Mundipagg/Paymentmodule/Model/Config/General.php
  app/code/community/Mundipagg/Paymentmodule/etc/config.xml
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/integrityCheck
  app/code/community/Mundipagg/Paymentmodule/etc/system.xml
Labels: Feature, Ready

#124 Telephone number mask support
  app/code/community/Mundipagg/Paymentmodule/Helper/Phone.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Standard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Paymentmethods/Standard.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/integrityCheck
  app/design/frontend/base/default/template/paymentmodule/form/partial/multibuyer.phtml
  app/locale/en_US/mundipagg_frontend_locale.csv
Labels: Feature, Ready, enhancement

#125 Fix value balance wrong behavior
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/integrityCheck
  features/BuyWithTwoCreditCard.feature
  js/mundipagg/paymentmodule.js
Labels: :bug: Bug, :ok_hand: Ready

#126 Fix virtual product handling
  app/code/community/Mundipagg/Paymentmodule/Helper/Address.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Standard.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/integrityCheck
Labels: :bug: Bug, :ok_hand: Ready
