Repository mundipagg/magento, pull requests merged in 2018-10, with the labels that each got.

#136 Implement boleto test automation
  .circleci/data/magento_module_install.sql
  features/BuyWithBoleto.feature
  features/BuyWithCreditCard.feature
  features/BuyWithTwoCreditCard.feature
Labels: :art: Enhancement, :ok_hand: Ready

#139 Show integrity violation information
  app/code/community/Mundipagg/Paymentmodule/Block/Adminhtml/Notification/Integrityviolation.php
  app/code/community/Mundipagg/Paymentmodule/Block/Adminhtml/Version.php
  app/code/community/Mundipagg/Paymentmodule/Model/Observer.php
  app/code/community/Mundipagg/Paymentmodule/etc/config.xml
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/integrityCheck
  app/design/adminhtml/default/default/layout/paymentmodule.xml
  app/design/adminhtml/default/default/template/paymentmodule/notifications/integrityViolation.phtml
Labels: :ok_hand: Ready, :sparkles: Feature

#140 Functional tests (2 credit cards, boleto + credit card, installments and saved)
  .circleci/config.yml
  .circleci/data/ciTestRunner.sh
  .circleci/data/magento_module_install.sql
  app/code/community/Mundipagg/Paymentmodule/Helper/Savedcreditcard.php
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/integrityCheck
  behat.yml
  composer.json
  features/BuyWithBoleto.feature
  features/BuyWithBoletoCreditCard.feature
  features/BuyWithCreditCard.feature
  features/BuyWithTwoCreditCard.feature
  features/bootstrap/FeatureContext.php
  features/partialScenarios.feature
  integrityPrePushCheck.sh
  theHook
Labels: :art: Enhancement, :construction: In development

#142 Create recurrence config admin screen
  .circleci/config.yml
  app/code/community/Mundipagg/Paymentmodule/etc/adminhtml.xml
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/integrityCheck
  app/code/community/Mundipagg/Paymentmodule/etc/system.xml
  app/locale/en_US/mundipagg_adminhtml_locale.csv
  app/locale/pt_BR/mundipagg_adminhtml_locale.csv
Labels: :ok_hand: Ready, :sparkles: Feature

#143 Create recurrence template screen
  app/code/community/Mundipagg/Paymentmodule/Block/Adminhtml/Recurrence/Template.php
  app/code/community/Mundipagg/Paymentmodule/Block/Adminhtml/Recurrence/Template/Grid.php
  app/code/community/Mundipagg/Paymentmodule/Model/Recurrencetemplate.php
  app/code/community/Mundipagg/Paymentmodule/Model/Resource/Recurrencetemplate.php
  app/code/community/Mundipagg/Paymentmodule/Model/Resource/Recurrencetemplate/Collection.php
  app/code/community/Mundipagg/Paymentmodule/controllers/Adminhtml/RecurrencetemplateController.php
  app/code/community/Mundipagg/Paymentmodule/etc/adminhtml.xml
  app/code/community/Mundipagg/Paymentmodule/etc/config.xml
  app/code/community/Mundipagg/Paymentmodule/etc/maintenance/integrityCheck
  app/code/community/Mundipagg/Paymentmodule/etc/recurrence/Aggregates/IAggregateRoot.php
  app/code/community/Mundipagg/Paymentmodule/etc/recurrence/Aggregates/Template/DueValueObject.php
  app/code/community/Mundipagg/Paymentmodule/etc/recurrence/Aggregates/Template/InstallmentValueObject.php
  app/code/community/Mundipagg/Paymentmodule/etc/recurrence/Aggregates/Template/PlanStatusValueObject.php
  app/code/community/Mundipagg/Paymentmodule/etc/recurrence/Aggregates/Template/RepetitionValueObject.php
  app/code/community/Mundipagg/Paymentmodule/etc/recurrence/Aggregates/Template/TemplateEntity.php
  app/code/community/Mundipagg/Paymentmodule/etc/recurrence/Aggregates/Template/TemplateRoot.php
  app/code/community/Mundipagg/Paymentmodule/etc/recurrence/Controller/Recurrence.php
  app/code/community/Mundipagg/Paymentmodule/etc/recurrence/Controller/Templates.php
  app/code/community/Mundipagg/Paymentmodule/etc/recurrence/Factories/TemplateEntityFactory.php
  app/code/community/Mundipagg/Paymentmodule/etc/recurrence/Factories/TemplateRootFactory.php
  app/code/community/Mundipagg/Paymentmodule/etc/recurrence/Repositories/AbstractRep.php
  app/code/community/Mundipagg/Paymentmodule/etc/recurrence/Repositories/Decorators/AbstractPlatformDatabaseDecorator.php
  app/code/community/Mundipagg/Paymentmodule/etc/recurrence/Repositories/Decorators/MagentoPlatformDatabaseDecorator.php
  app/code/community/Mundipagg/Paymentmodule/etc/recurrence/Repositories/TemplateRepository.php
  app/code/community/Mundipagg/Paymentmodule/etc/system.xml
  app/code/community/Mundipagg/Paymentmodule/sql/mundipagg_paymentmodule_setup/install-0.1.0.php
  app/code/community/Mundipagg/Paymentmodule/sql/mundipagg_paymentmodule_setup/upgrade-1.8.0-1.9.0.php
  app/design/adminhtml/default/default/layout/paymentmodule.xml
  app/design/adminhtml/default/default/template/paymentmodule/extras.phtml
  app/design/adminhtml/default/default/template/paymentmodule/recurrencetemplate.phtml
  composer.json
Labels: :ok_hand: Ready, :sparkles: Feature
