Repository mundipagg/magento, pull requests merged in 2018-05, with the labels that each got.

#75 Fix configurable product
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Boleto.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Paymentmethods/Standard.php
Labels: Ready, bug

#76 Change module routes
  .github/PULL_REQUEST_TEMPLATE.md
  app/code/community/Mundipagg/Paymentmodule/etc/config.xml
  js/mundipagg/paymentmodule.js
Labels: Ready, enhancement

#77 Create module version updater
  README.md
  RoboFile.php
  composer.json
  composer.lock
  mundipagg_payment_module.xml
Labels: Ready, enhancement

#78 Fix compatibility with the oldest module
  app/code/community/Mundipagg/Paymentmodule/Block/Checkout/Information.php
  app/code/community/Mundipagg/Paymentmodule/Model/Observer.php
  app/design/frontend/base/default/layout/paymentmodule.xml
Labels: Ready, bug

#80 Bug/244 filling correct value configured of capture
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Boleto.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Standard.php
  app/code/community/Mundipagg/Paymentmodule/etc/system.xml
Labels: Ready, bug

#82 Deal with charge response
  app/code/community/Mundipagg/Paymentmodule/Helper/Charge.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Chargeoperations.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Redirect.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Order.php
  app/code/community/Mundipagg/Paymentmodule/Model/Core/Charge.php
  app/code/community/Mundipagg/Paymentmodule/Model/Paymentmethods/Standard.php
  app/code/community/Mundipagg/Paymentmodule/controllers/WebhookController.php
Labels: Ready, bug

#83 Create charge screen
  app/code/community/Mundipagg/Paymentmodule/Block/Adminhtml/Order/Charge.php
  app/code/community/Mundipagg/Paymentmodule/Block/Adminhtml/Order/Charge/Grid.php
  app/code/community/Mundipagg/Paymentmodule/Model/Observer.php
  app/code/community/Mundipagg/Paymentmodule/Model/Standard.php
  app/code/community/Mundipagg/Paymentmodule/controllers/Adminhtml/ChargeController.php
  app/code/community/Mundipagg/Paymentmodule/etc/config.xml
  app/locale/en_US/mundipagg_adminhtml_locale.csv
  app/locale/pt_BR/mundipagg_adminhtml_locale.csv
  modman
Labels: Feature, Ready

#84 Add Multiple checkout module support
  app/code/community/Mundipagg/Paymentmodule/Block/Adminhtml/Order/Charge/Grid.php
  app/code/community/Mundipagg/Paymentmodule/Model/Standard.php
  app/design/frontend/base/default/layout/paymentmodule.xml
  app/design/frontend/base/default/template/paymentmodule/form/builder.phtml
  app/design/frontend/base/default/template/paymentmodule/form/partial/creditcard.phtml
  js/mundipagg/AbstractCheckoutModuleHandler.js
  js/mundipagg/OSCCheckoutModuleHandler.js
  js/mundipagg/OnepageCheckoutModuleHandler.js
  js/mundipagg/paymentmodule.js
Labels: Feature, Ready

#86 Apply interest on the order
  app/code/community/Mundipagg/Paymentmodule/Block/Adminhtml/Sales/Order/Totals.php
  app/code/community/Mundipagg/Paymentmodule/Block/Sales/Order/Totals.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Interest.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Paymentformat.php
  app/code/community/Mundipagg/Paymentmodule/Model/Core/Order.php
  app/code/community/Mundipagg/Paymentmodule/Model/Standard.php
  app/code/community/Mundipagg/Paymentmodule/etc/config.xml
  js/mundipagg/paymentmodule.js
Labels: Ready, bug

#88 Fix installments calculations on frontend
  app/code/community/Mundipagg/Paymentmodule/Block/Base.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Installment.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Monetary.php
  js/mundipagg/paymentmodule.js
Labels: Ready, bug

#89 Fix saved card to guest
  app/design/frontend/base/default/template/paymentmodule/form/partial/creditcard.phtml
Labels: Ready, bug
