Repository mundipagg/magento, pull requests merged in 2018-03, with the labels that each got.

#46 Refatorar backend
  app/code/community/Mundipagg/Paymentmodule/Block/Form/Builder.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Chargeoperations.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Boleto.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Boletocc.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Customer.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Order.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Standard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Twocreditcards.php
  app/code/community/Mundipagg/Paymentmodule/Model/Boleto.php
  app/code/community/Mundipagg/Paymentmodule/Model/Boletocc.php
  app/code/community/Mundipagg/Paymentmodule/Model/Config/Twocreditcards.php
  app/code/community/Mundipagg/Paymentmodule/Model/Core/Charge.php
  app/code/community/Mundipagg/Paymentmodule/Model/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Paymentmethods/Boleto.php
  app/code/community/Mundipagg/Paymentmodule/Model/Paymentmethods/Boletocc.php
  app/code/community/Mundipagg/Paymentmodule/Model/Paymentmethods/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Paymentmethods/Standard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Standard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Twocreditcards.php
  app/code/community/Mundipagg/Paymentmodule/controllers/PaymentController.php
  app/code/community/Mundipagg/Paymentmodule/etc/system.xml
  app/design/frontend/base/default/template/paymentmodule/form/builder.phtml
  app/design/frontend/base/default/template/paymentmodule/form/partial/boleto.phtml
  app/design/frontend/base/default/template/paymentmodule/form/partial/creditcard.phtml
  js/mundipagg/paymentmodule.js
Labels: enhancement

#45 :art: improve assign data
  app/code/community/Mundipagg/Paymentmodule/Block/Form/Builder.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Boleto.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Standard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Boleto.php
  app/code/community/Mundipagg/Paymentmodule/Model/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Paymentmethods/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Paymentmethods/Standard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Standard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Twocreditcards.php
  app/code/community/Mundipagg/Paymentmodule/controllers/PaymentController.php
  app/design/frontend/base/default/template/paymentmodule/form/builder.phtml
  app/design/frontend/base/default/template/paymentmodule/form/partial/boleto.phtml
  js/mundipagg/paymentmodule.js
Labels: Feature

#49 #76 create install script
  app/code/community/Mundipagg/Paymentmodule/Model/Resource/SavedCreditCard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Resource/SavedCreditCard/Collection.php
  app/code/community/Mundipagg/Paymentmodule/Model/SavedCreditCard.php
  app/code/community/Mundipagg/Paymentmodule/etc/config.xml
  app/code/community/Mundipagg/Paymentmodule/sql/mundipagg/install-1.0.0.php
  app/code/community/Mundipagg/Paymentmodule/sql/mundipagg_paymentmodule_setup/install-0.1.0.php
  modman
Labels: Feature

#50 #76 Fix config.xml.
  app/code/community/Mundipagg/Paymentmodule/etc/config.xml
Labels: bug

#51 Fix GitHub templates
  .github/ISSUE-TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  PULLREQUEST-TEMPLATE.md
Labels: bug

#52 mundipagg/plug-team#76 save credit card
  app/code/community/Mundipagg/Paymentmodule/Block/Form/Builder.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Savedcreditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Order.php
  app/code/community/Mundipagg/Paymentmodule/Model/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Resource/SavedCreditCard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Resource/SavedCreditCard/Collection.php
  app/code/community/Mundipagg/Paymentmodule/Model/Resource/Savedcreditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Resource/Savedcreditcard/Collection.php
  app/code/community/Mundipagg/Paymentmodule/Model/SavedCreditCard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Savedcreditcard.php
  app/code/community/Mundipagg/Paymentmodule/etc/config.xml
  app/code/community/Mundipagg/Paymentmodule/sql/mundipagg_paymentmodule_setup/install-0.1.0.php
  app/design/frontend/base/default/template/paymentmodule/form/partial/creditcard.phtml
  js/mundipagg/paymentmodule.js
  skin/frontend/base/default/css/paymentmodule.css
Labels: Feature, In development

#53 Saved Credit cards wallet and javascript adjusts.
  app/code/community/Mundipagg/Paymentmodule/Block/Customer/Account/Wallet.php
  app/code/community/Mundipagg/Paymentmodule/Block/Form/Builder.php
  app/code/community/Mundipagg/Paymentmodule/Block/Form/Partial/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Chargeoperations.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Installment.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Log.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Order.php
  app/code/community/Mundipagg/Paymentmodule/Helper/Savedcreditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Boleto.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Order.php
  app/code/community/Mundipagg/Paymentmodule/Model/Config/Card.php
  app/code/community/Mundipagg/Paymentmodule/Model/Config/General.php
  app/code/community/Mundipagg/Paymentmodule/Model/Core/Base.php
  app/code/community/Mundipagg/Paymentmodule/Model/Core/Charge.php
  app/code/community/Mundipagg/Paymentmodule/Model/Core/Order.php
  app/code/community/Mundipagg/Paymentmodule/Model/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Enum/Orderhistory.php
  app/code/community/Mundipagg/Paymentmodule/Model/Observer.php
  app/code/community/Mundipagg/Paymentmodule/Model/Paymentmethods/Standard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Standard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Twocreditcards.php
  app/code/community/Mundipagg/Paymentmodule/controllers/WalletController.php
  app/code/community/Mundipagg/Paymentmodule/controllers/WebhookController.php
  app/code/community/Mundipagg/Paymentmodule/etc/config.xml
  app/code/community/Mundipagg/Paymentmodule/etc/system.xml
  app/design/frontend/base/default/layout/paymentmodule.xml
  app/design/frontend/base/default/template/paymentmodule/customer/account/wallet.phtml
  app/design/frontend/base/default/template/paymentmodule/form/partial/creditcard.phtml
  js/mundipagg/paymentmodule.js
Labels: Feature, Ready

#54 Boleto link on checkout success
  app/code/community/Mundipagg/Paymentmodule/Block/Checkout/Information.php
  app/code/community/Mundipagg/Paymentmodule/Model/Observer.php
  app/code/community/Mundipagg/Paymentmodule/Model/Paymentmethods/Standard.php
  app/code/community/Mundipagg/Paymentmodule/controllers/WalletController.php
  app/code/community/Mundipagg/Paymentmodule/etc/config.xml
  app/design/frontend/base/default/layout/paymentmodule.xml
  app/design/frontend/base/default/template/paymentmodule/checkout/information.phtml
  app/design/frontend/base/default/template/paymentmodule/checkout/success/payment/success.phtml
Labels: Feature, Ready

#55 Fix config title not showed on checkout
  app/code/community/Mundipagg/Paymentmodule/Block/Form/Builder.php
  app/code/community/Mundipagg/Paymentmodule/Model/Boleto.php
  app/code/community/Mundipagg/Paymentmodule/Model/Boletocc.php
  app/code/community/Mundipagg/Paymentmodule/Model/Config/Card.php
  app/code/community/Mundipagg/Paymentmodule/Model/Config/Twocreditcards.php
  app/code/community/Mundipagg/Paymentmodule/Model/Creditcard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Standard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Twocreditcards.php
  app/code/community/Mundipagg/Paymentmodule/etc/system.xml
Labels: Ready, bug

#56 Value balance on multipayment
  app/code/community/Mundipagg/Paymentmodule/Block/Form/Builder.php
  app/design/frontend/base/default/template/paymentmodule/form/builder.phtml
  js/mundipagg/paymentmodule.js
Labels: Feature, Ready
