Repository mundipagg/magento, pull requests merged in 2019-06, with the labels that each got.

#183 Create sort order to payment methods
  app/code/community/Mundipagg/Paymentmodule/Model/Config/Boleto.php
  app/code/community/Mundipagg/Paymentmodule/Model/Config/Boletocc.php
  app/code/community/Mundipagg/Paymentmodule/Model/Config/Card.php
  app/code/community/Mundipagg/Paymentmodule/Model/Config/Twocreditcards.php
  app/code/community/Mundipagg/Paymentmodule/Model/Config/Voucher.php
  app/code/community/Mundipagg/Paymentmodule/Model/Standard.php
  app/code/community/Mundipagg/Paymentmodule/etc/config.xml
  app/code/community/Mundipagg/Paymentmodule/etc/system.xml
  js/mundipagg/paymentmodule.js
Labels: :bug: Bug, :ok_hand: Ready, :sparkles: Feature

#184 Fix the email send when has a new order
  app/code/community/Mundipagg/Paymentmodule/Model/Paymentmethods/Standard.php
Labels: :bug: Bug, :ok_hand: Ready

#187 Fix class instance call
  .circleci/data/setCorrectCoreBranch.sh
  app/code/community/Mundipagg/Paymentmodule/Concrete/MagentoModuleCoreSetup.php
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Standard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Paymentmethods/Standard.php
  composer.lock
Labels: :bug: Bug, :ok_hand: Ready

#188 Merge develop into master
  .circleci/data/setCorrectCoreBranch.sh
  app/code/community/Mundipagg/Paymentmodule/Concrete/MagentoModuleCoreSetup.php
  app/code/community/Mundipagg/Paymentmodule/Concrete/integrityData
  app/code/community/Mundipagg/Paymentmodule/Model/Api/Standard.php
  app/code/community/Mundipagg/Paymentmodule/Model/Paymentmethods/Standard.php
  app/code/community/Mundipagg/Paymentmodule/etc/config.xml
  composer.json
  composer.lock
  mundipagg_payment_module.xml
Labels: :bug: Bug, :ok_hand: Ready

#189 Fix modman link
  app/code/community/Mundipagg/Paymentmodule/Concrete/integrityData
  modman
Labels: :art: Enhancement
